name: Test and Build

on:
  push:
    branches:
      - main
    paths:
      - "**/*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Docker Setup
        uses: docker/setup-buildx-action@v2

      - name: Install dependencies
        run: |
          npm install

      - name: Run Linting tests
        run: |
          npm run lint

      - name: Docker Credentials
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker tag
        id: version
        run: |
          VERSION=v$(date +"%Y%m%d%H%M%S")
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build Docker Image
        run: |
          docker build . -t michealken30/spotify-app:${{ env.VERSION }}

      - name: Push Docker Image
        run: |
          docker push michealken30/spotify-app:${{ env.VERSION }}

      # - name: Update K8s Manifests
      #   run: |
      #     cat deploy/deploy.yaml
      #     sed -i "s|image: michealken30/spotify-app:.*|image: michealken30/spotify-app:${{ env.VERSION }}|g" deploy/deploy.yaml
      #     cat deploy/deploy.yaml

      # - name: Commit the changes
      #   run: |
      #     git config --global user.email "<>"
      #     git config --global user.name "GitHub Actions Bot"
      #     git add deploy/deploy.yaml
      #     git commit -m "Update deploy.yaml with new image version - ${{ env.VERSION }}"
      #     git push origin main
